// react-hello-world/hello-world-ts/src/App.tsx
import * as React from 'react';
import './App.css';

import logo from './logo.svg';

class App extends React.Component {
  public render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React, dude!</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.tsx</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;

// angular-first-app/src/app/app.ts
import { Component } from '@angular/core';
import { Home } from './home/home';

@Component({
    selector: 'app-root',
    imports: [Home],
    template: `
    <main>
        <header class="brand-name">
        <img class="brand-logo" src="/public/logo.svg" alt="logo" aria-hidden="true" />
        </header>
        <section class="content">
            <app-home />
        </section>
    </main>
    `,
    styleUrls: ['./app.css'],
})
export class App {
    title = 'homes';
}
